# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wicker25/Progetti/C-C++/Serotonina

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wicker25/Progetti/C-C++/Serotonina

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wicker25/Progetti/C-C++/Serotonina/CMakeFiles /home/wicker25/Progetti/C-C++/Serotonina/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wicker25/Progetti/C-C++/Serotonina/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named serotonina

# Build rule for target.
serotonina: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serotonina
.PHONY : serotonina

# fast build rule for target.
serotonina/fast:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/build
.PHONY : serotonina/fast

#=============================================================================
# Target rules for targets named serotonina_plot

# Build rule for target.
serotonina_plot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serotonina_plot
.PHONY : serotonina_plot

# fast build rule for target.
serotonina_plot/fast:
	$(MAKE) -f CMakeFiles/serotonina_plot.dir/build.make CMakeFiles/serotonina_plot.dir/build
.PHONY : serotonina_plot/fast

#=============================================================================
# Target rules for targets named st_face_recognition

# Build rule for target.
st_face_recognition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 st_face_recognition
.PHONY : st_face_recognition

# fast build rule for target.
st_face_recognition/fast:
	$(MAKE) -f CMakeFiles/st_face_recognition.dir/build.make CMakeFiles/st_face_recognition.dir/build
.PHONY : st_face_recognition/fast

#=============================================================================
# Target rules for targets named st_gym

# Build rule for target.
st_gym: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 st_gym
.PHONY : st_gym

# fast build rule for target.
st_gym/fast:
	$(MAKE) -f CMakeFiles/st_gym.dir/build.make CMakeFiles/st_gym.dir/build
.PHONY : st_gym/fast

#=============================================================================
# Target rules for targets named st_ocr

# Build rule for target.
st_ocr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 st_ocr
.PHONY : st_ocr

# fast build rule for target.
st_ocr/fast:
	$(MAKE) -f CMakeFiles/st_ocr.dir/build.make CMakeFiles/st_ocr.dir/build
.PHONY : st_ocr/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

src/extra/face-recognition.o: src/extra/face-recognition.cpp.o
.PHONY : src/extra/face-recognition.o

# target to build an object file
src/extra/face-recognition.cpp.o:
	$(MAKE) -f CMakeFiles/st_face_recognition.dir/build.make CMakeFiles/st_face_recognition.dir/src/extra/face-recognition.cpp.o
.PHONY : src/extra/face-recognition.cpp.o

src/extra/face-recognition.i: src/extra/face-recognition.cpp.i
.PHONY : src/extra/face-recognition.i

# target to preprocess a source file
src/extra/face-recognition.cpp.i:
	$(MAKE) -f CMakeFiles/st_face_recognition.dir/build.make CMakeFiles/st_face_recognition.dir/src/extra/face-recognition.cpp.i
.PHONY : src/extra/face-recognition.cpp.i

src/extra/face-recognition.s: src/extra/face-recognition.cpp.s
.PHONY : src/extra/face-recognition.s

# target to generate assembly for a file
src/extra/face-recognition.cpp.s:
	$(MAKE) -f CMakeFiles/st_face_recognition.dir/build.make CMakeFiles/st_face_recognition.dir/src/extra/face-recognition.cpp.s
.PHONY : src/extra/face-recognition.cpp.s

src/extra/gym.o: src/extra/gym.cpp.o
.PHONY : src/extra/gym.o

# target to build an object file
src/extra/gym.cpp.o:
	$(MAKE) -f CMakeFiles/st_gym.dir/build.make CMakeFiles/st_gym.dir/src/extra/gym.cpp.o
.PHONY : src/extra/gym.cpp.o

src/extra/gym.i: src/extra/gym.cpp.i
.PHONY : src/extra/gym.i

# target to preprocess a source file
src/extra/gym.cpp.i:
	$(MAKE) -f CMakeFiles/st_gym.dir/build.make CMakeFiles/st_gym.dir/src/extra/gym.cpp.i
.PHONY : src/extra/gym.cpp.i

src/extra/gym.s: src/extra/gym.cpp.s
.PHONY : src/extra/gym.s

# target to generate assembly for a file
src/extra/gym.cpp.s:
	$(MAKE) -f CMakeFiles/st_gym.dir/build.make CMakeFiles/st_gym.dir/src/extra/gym.cpp.s
.PHONY : src/extra/gym.cpp.s

src/extra/ocr.o: src/extra/ocr.cpp.o
.PHONY : src/extra/ocr.o

# target to build an object file
src/extra/ocr.cpp.o:
	$(MAKE) -f CMakeFiles/st_ocr.dir/build.make CMakeFiles/st_ocr.dir/src/extra/ocr.cpp.o
.PHONY : src/extra/ocr.cpp.o

src/extra/ocr.i: src/extra/ocr.cpp.i
.PHONY : src/extra/ocr.i

# target to preprocess a source file
src/extra/ocr.cpp.i:
	$(MAKE) -f CMakeFiles/st_ocr.dir/build.make CMakeFiles/st_ocr.dir/src/extra/ocr.cpp.i
.PHONY : src/extra/ocr.cpp.i

src/extra/ocr.s: src/extra/ocr.cpp.s
.PHONY : src/extra/ocr.s

# target to generate assembly for a file
src/extra/ocr.cpp.s:
	$(MAKE) -f CMakeFiles/st_ocr.dir/build.make CMakeFiles/st_ocr.dir/src/extra/ocr.cpp.s
.PHONY : src/extra/ocr.cpp.s

src/extra/plot.o: src/extra/plot.cpp.o
.PHONY : src/extra/plot.o

# target to build an object file
src/extra/plot.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina_plot.dir/build.make CMakeFiles/serotonina_plot.dir/src/extra/plot.cpp.o
.PHONY : src/extra/plot.cpp.o

src/extra/plot.i: src/extra/plot.cpp.i
.PHONY : src/extra/plot.i

# target to preprocess a source file
src/extra/plot.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina_plot.dir/build.make CMakeFiles/serotonina_plot.dir/src/extra/plot.cpp.i
.PHONY : src/extra/plot.cpp.i

src/extra/plot.s: src/extra/plot.cpp.s
.PHONY : src/extra/plot.s

# target to generate assembly for a file
src/extra/plot.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina_plot.dir/build.make CMakeFiles/serotonina_plot.dir/src/extra/plot.cpp.s
.PHONY : src/extra/plot.cpp.s

src/mod/batch.o: src/mod/batch.cpp.o
.PHONY : src/mod/batch.o

# target to build an object file
src/mod/batch.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/batch.cpp.o
.PHONY : src/mod/batch.cpp.o

src/mod/batch.i: src/mod/batch.cpp.i
.PHONY : src/mod/batch.i

# target to preprocess a source file
src/mod/batch.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/batch.cpp.i
.PHONY : src/mod/batch.cpp.i

src/mod/batch.s: src/mod/batch.cpp.s
.PHONY : src/mod/batch.s

# target to generate assembly for a file
src/mod/batch.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/batch.cpp.s
.PHONY : src/mod/batch.cpp.s

src/mod/irpropm.o: src/mod/irpropm.cpp.o
.PHONY : src/mod/irpropm.o

# target to build an object file
src/mod/irpropm.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/irpropm.cpp.o
.PHONY : src/mod/irpropm.cpp.o

src/mod/irpropm.i: src/mod/irpropm.cpp.i
.PHONY : src/mod/irpropm.i

# target to preprocess a source file
src/mod/irpropm.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/irpropm.cpp.i
.PHONY : src/mod/irpropm.cpp.i

src/mod/irpropm.s: src/mod/irpropm.cpp.s
.PHONY : src/mod/irpropm.s

# target to generate assembly for a file
src/mod/irpropm.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/irpropm.cpp.s
.PHONY : src/mod/irpropm.cpp.s

src/mod/irpropp.o: src/mod/irpropp.cpp.o
.PHONY : src/mod/irpropp.o

# target to build an object file
src/mod/irpropp.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/irpropp.cpp.o
.PHONY : src/mod/irpropp.cpp.o

src/mod/irpropp.i: src/mod/irpropp.cpp.i
.PHONY : src/mod/irpropp.i

# target to preprocess a source file
src/mod/irpropp.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/irpropp.cpp.i
.PHONY : src/mod/irpropp.cpp.i

src/mod/irpropp.s: src/mod/irpropp.cpp.s
.PHONY : src/mod/irpropp.s

# target to generate assembly for a file
src/mod/irpropp.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/irpropp.cpp.s
.PHONY : src/mod/irpropp.cpp.s

src/mod/rprop.o: src/mod/rprop.cpp.o
.PHONY : src/mod/rprop.o

# target to build an object file
src/mod/rprop.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rprop.cpp.o
.PHONY : src/mod/rprop.cpp.o

src/mod/rprop.i: src/mod/rprop.cpp.i
.PHONY : src/mod/rprop.i

# target to preprocess a source file
src/mod/rprop.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rprop.cpp.i
.PHONY : src/mod/rprop.cpp.i

src/mod/rprop.s: src/mod/rprop.cpp.s
.PHONY : src/mod/rprop.s

# target to generate assembly for a file
src/mod/rprop.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rprop.cpp.s
.PHONY : src/mod/rprop.cpp.s

src/mod/rpropm.o: src/mod/rpropm.cpp.o
.PHONY : src/mod/rpropm.o

# target to build an object file
src/mod/rpropm.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rpropm.cpp.o
.PHONY : src/mod/rpropm.cpp.o

src/mod/rpropm.i: src/mod/rpropm.cpp.i
.PHONY : src/mod/rpropm.i

# target to preprocess a source file
src/mod/rpropm.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rpropm.cpp.i
.PHONY : src/mod/rpropm.cpp.i

src/mod/rpropm.s: src/mod/rpropm.cpp.s
.PHONY : src/mod/rpropm.s

# target to generate assembly for a file
src/mod/rpropm.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rpropm.cpp.s
.PHONY : src/mod/rpropm.cpp.s

src/mod/rpropp.o: src/mod/rpropp.cpp.o
.PHONY : src/mod/rpropp.o

# target to build an object file
src/mod/rpropp.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rpropp.cpp.o
.PHONY : src/mod/rpropp.cpp.o

src/mod/rpropp.i: src/mod/rpropp.cpp.i
.PHONY : src/mod/rpropp.i

# target to preprocess a source file
src/mod/rpropp.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rpropp.cpp.i
.PHONY : src/mod/rpropp.cpp.i

src/mod/rpropp.s: src/mod/rpropp.cpp.s
.PHONY : src/mod/rpropp.s

# target to generate assembly for a file
src/mod/rpropp.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/mod/rpropp.cpp.s
.PHONY : src/mod/rpropp.cpp.s

src/network.o: src/network.cpp.o
.PHONY : src/network.o

# target to build an object file
src/network.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/network.cpp.o
.PHONY : src/network.cpp.o

src/network.i: src/network.cpp.i
.PHONY : src/network.i

# target to preprocess a source file
src/network.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/network.cpp.i
.PHONY : src/network.cpp.i

src/network.s: src/network.cpp.s
.PHONY : src/network.s

# target to generate assembly for a file
src/network.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/network.cpp.s
.PHONY : src/network.cpp.s

src/trainer.o: src/trainer.cpp.o
.PHONY : src/trainer.o

# target to build an object file
src/trainer.cpp.o:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/trainer.cpp.o
.PHONY : src/trainer.cpp.o

src/trainer.i: src/trainer.cpp.i
.PHONY : src/trainer.i

# target to preprocess a source file
src/trainer.cpp.i:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/trainer.cpp.i
.PHONY : src/trainer.cpp.i

src/trainer.s: src/trainer.cpp.s
.PHONY : src/trainer.s

# target to generate assembly for a file
src/trainer.cpp.s:
	$(MAKE) -f CMakeFiles/serotonina.dir/build.make CMakeFiles/serotonina.dir/src/trainer.cpp.s
.PHONY : src/trainer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... serotonina"
	@echo "... serotonina_plot"
	@echo "... st_face_recognition"
	@echo "... st_gym"
	@echo "... st_ocr"
	@echo "... uninstall"
	@echo "... src/extra/face-recognition.o"
	@echo "... src/extra/face-recognition.i"
	@echo "... src/extra/face-recognition.s"
	@echo "... src/extra/gym.o"
	@echo "... src/extra/gym.i"
	@echo "... src/extra/gym.s"
	@echo "... src/extra/ocr.o"
	@echo "... src/extra/ocr.i"
	@echo "... src/extra/ocr.s"
	@echo "... src/extra/plot.o"
	@echo "... src/extra/plot.i"
	@echo "... src/extra/plot.s"
	@echo "... src/mod/batch.o"
	@echo "... src/mod/batch.i"
	@echo "... src/mod/batch.s"
	@echo "... src/mod/irpropm.o"
	@echo "... src/mod/irpropm.i"
	@echo "... src/mod/irpropm.s"
	@echo "... src/mod/irpropp.o"
	@echo "... src/mod/irpropp.i"
	@echo "... src/mod/irpropp.s"
	@echo "... src/mod/rprop.o"
	@echo "... src/mod/rprop.i"
	@echo "... src/mod/rprop.s"
	@echo "... src/mod/rpropm.o"
	@echo "... src/mod/rpropm.i"
	@echo "... src/mod/rpropm.s"
	@echo "... src/mod/rpropp.o"
	@echo "... src/mod/rpropp.i"
	@echo "... src/mod/rpropp.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/trainer.o"
	@echo "... src/trainer.i"
	@echo "... src/trainer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

