# - Try to find Serotonina

#  SEROTONINA_INCLUDE_DIRS - where to find curl/curl.h, etc.
#  SEROTONINA_LIBRARIES    - List of libraries when using curl.
#  SEROTONINA_FOUND        - True if curl found.

FIND_PATH( SEROTONINA_INCLUDE_DIR NAMES serotonina )
MARK_AS_ADVANCED( SEROTONINA_INCLUDE_DIR )

FIND_LIBRARY( SEROTONINA_LIBRARY NAMES serotonina )
MARK_AS_ADVANCED( SEROTONINA_LIBRARY )

INCLUDE( FindPackageHandleStandardArgs )

FIND_PACKAGE_HANDLE_STANDARD_ARGS( SEROTONINA DEFAULT_MSG SEROTONINA_LIBRARY SEROTONINA_INCLUDE_DIR )

IF ( SEROTONINA_FOUND )

  SET( SEROTONINA_LIBRARIES ${SEROTONINA_LIBRARY} )
  SET( SEROTONINA_INCLUDE_DIRS ${SEROTONINA_INCLUDE_DIR} )

ENDIF ( SEROTONINA_FOUND )

